// File generated by FlutterFire CLI (clean, single definition).
// ignore_for_file: prefer_single_quotes, constant_identifier_names
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Update these values with your Firebase project credentials if needed.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNoY0GX3vXYBFE_fKES3h38B8XtcIolB0',
    appId: '1:217873707244:android:b35facf72ef53e8a4eb5c9',
    messagingSenderId: '217873707244',
    projectId: 'kalori-takip-8473f',
    storageBucket: 'kalori-takip-8473f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfvmvLpblkxdQHcMgNn7cXj5bnnlrSFz4',
    appId: '1:217873707244:ios:de765aa8bc763cc94eb5c9',
    messagingSenderId: '217873707244',
    projectId: 'kalori-takip-8473f',
    storageBucket: 'kalori-takip-8473f.firebasestorage.app',
    iosBundleId: 'com.yusuf.kaloritakip',
  );

  // Fallback to iOS values for macOS if you don't have separate macOS credentials.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfvmvLpblkxdQHcMgNn7cXj5bnnlrSFz4',
    appId: '1:217873707244:ios:de765aa8bc763cc94eb5c9',
    messagingSenderId: '217873707244',
    projectId: 'kalori-takip-8473f',
    storageBucket: 'kalori-takip-8473f.firebasestorage.app',
    iosBundleId: 'com.yusuf.kaloritakip',
  );
}
